
import __ASTRO_IMAGE_IMPORT_Z11qGK6 from "./images/planet_painter_snapshot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fsoftware%2Fplanet-painter.md";
import __ASTRO_IMAGE_IMPORT_JLRFi from "./images/stoor_website_snapshot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fsoftware%2Fstoor.md";
import __ASTRO_IMAGE_IMPORT_Z1pUH2B from "./images/espresso_expose_header.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fespresso-expose.md";
import __ASTRO_IMAGE_IMPORT_I5sGa from "./images/storyforgers_website_snapshot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fstorytelling%2Fstoryforgers.md";
import __ASTRO_IMAGE_IMPORT_Z2lMO0g from "./images/deconstructing_transformers.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabstracts%2Fdeconstructing_transformers.md";
import __ASTRO_IMAGE_IMPORT_Z2hoCnI from "./images/digital_natives_snapshot.png?astroContentImageFlag=&importer=src%2Fcontent%2Fabstracts%2Fdigital-natives.md";
import __ASTRO_IMAGE_IMPORT_Z25XP3C from "./images/espresso_expose_header.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fabstracts%2Fespresso-expose.md";
import __ASTRO_IMAGE_IMPORT_Z1PVuRo from "./images/imagine_me_snapshot.png?astroContentImageFlag=&importer=src%2Fcontent%2Fabstracts%2Fimagine-me.md";
import __ASTRO_IMAGE_IMPORT_1ppcXc from "./images/planet_painter_snapshot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabstracts%2Fplanet-painter.md";
import __ASTRO_IMAGE_IMPORT_29TNPw from "./images/stoor_website_snapshot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabstracts%2Fstoor.md";
import __ASTRO_IMAGE_IMPORT_ZPQbDS from "../storytelling/images/storyforgers_website_snapshot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabstracts%2Fstoryforgers.md";
export default new Map([["./images/planet_painter_snapshot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fsoftware%2Fplanet-painter.md", __ASTRO_IMAGE_IMPORT_Z11qGK6], ["./images/stoor_website_snapshot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fsoftware%2Fstoor.md", __ASTRO_IMAGE_IMPORT_JLRFi], ["./images/espresso_expose_header.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fart%2Fespresso-expose.md", __ASTRO_IMAGE_IMPORT_Z1pUH2B], ["./images/storyforgers_website_snapshot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fstorytelling%2Fstoryforgers.md", __ASTRO_IMAGE_IMPORT_I5sGa], ["./images/deconstructing_transformers.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabstracts%2Fdeconstructing_transformers.md", __ASTRO_IMAGE_IMPORT_Z2lMO0g], ["./images/digital_natives_snapshot.png?astroContentImageFlag=&importer=src%2Fcontent%2Fabstracts%2Fdigital-natives.md", __ASTRO_IMAGE_IMPORT_Z2hoCnI], ["./images/espresso_expose_header.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fabstracts%2Fespresso-expose.md", __ASTRO_IMAGE_IMPORT_Z25XP3C], ["./images/imagine_me_snapshot.png?astroContentImageFlag=&importer=src%2Fcontent%2Fabstracts%2Fimagine-me.md", __ASTRO_IMAGE_IMPORT_Z1PVuRo], ["./images/planet_painter_snapshot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabstracts%2Fplanet-painter.md", __ASTRO_IMAGE_IMPORT_1ppcXc], ["./images/stoor_website_snapshot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabstracts%2Fstoor.md", __ASTRO_IMAGE_IMPORT_29TNPw], ["../storytelling/images/storyforgers_website_snapshot.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabstracts%2Fstoryforgers.md", __ASTRO_IMAGE_IMPORT_ZPQbDS]]);
		